// <auto-generated />
using System;
using CaixaTroco.Infraestrutura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaixaTroco.Api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210609035223_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CaixaTroco.Dominio.Entidades.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("CaixaTroco.Dominio.Entidades.TransacaoCedula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("TransacaoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("TransacaoId");

                    b.ToTable("TransacaoCedulas");
                });

            modelBuilder.Entity("CaixaTroco.Dominio.Entidades.TransacaoCedula", b =>
                {
                    b.HasOne("CaixaTroco.Dominio.Entidades.Transacao", null)
                        .WithMany("Cedulas")
                        .HasForeignKey("TransacaoId");
                });

            modelBuilder.Entity("CaixaTroco.Dominio.Entidades.Transacao", b =>
                {
                    b.Navigation("Cedulas");
                });
#pragma warning restore 612, 618
        }
    }
}
